export const INTERN_ENDPOINTS = {
  BASE: '/api/interns',
  LIST: '/api/interns',
  CREATE: '/api/interns',
  DETAIL: (id: number | string) => `/api/interns/${id}`,
  UPDATE: (id: number | string) => `/api/interns/${id}`,
  STATUS: (id: number | string) => `/api/interns/${id}/status`,
  DECISION: (id: number | string) => `/api/interns/${id}/decision`,
  RESEND_DECISION_EMAIL: (id: number | string) => `/api/interns/${id}/resend-decision-email`,
  DOCUMENTS: (internCode: string) => `/api/interns/${internCode}/documents`,
  APPLY: '/api/interns/apply',
  MENTORS: '/api/interns/mentors',
  ASSIGN_MENTOR: (id: number | string) => `/api/interns/${id}/assign-mentor`,
  REVOKE_MENTOR: (id: number | string) => `/api/interns/${id}/mentor`,
  MENTOR_HISTORY: (id: number | string) => `/api/interns/${id}/mentor-history`,
  MENTOR_INTERNS: (mentorId: number | string) => `/api/interns/mentors/${mentorId}/interns`,
  RESEND_MENTOR_INVITATION: (mentorId: number | string) => `/api/interns/mentors/${mentorId}/resend-invitation`,
  MY_PROFILE: '/api/interns/my-profile',
  WEEKLY_ASSESSMENTS: (internCode: string) => `/api/interns/${internCode}/weekly-assessments`,
  EVALUATIONS: (internCode: string) => `/api/interns/${internCode}/evaluations`,
  MENTOR_OVERVIEW: '/api/mentors/my-interns/overview',
  // TM-21: Báo cáo tuần Thực tập sinh
  MY_WEEKLY_REPORTS_TIMELINE: '/api/interns/my-weekly-reports',
  MY_WEEKLY_REPORTS_SUGGESTED_TASKS: (weekNumber: number) => `/api/interns/my-weekly-reports/${weekNumber}/kanban-tasks`,
  MY_WEEKLY_REPORT_DETAIL: (weekNumber: number) => `/api/interns/my-weekly-reports/${weekNumber}`,
  MY_WEEKLY_REPORT_SAVE: '/api/interns/my-weekly-reports',
  MY_WEEKLY_REPORT_SUBMIT: (weekNumber: number) => `/api/interns/my-weekly-reports/${weekNumber}/submit`,
  MY_WEEKLY_REPORT_UPDATE: (weekNumber: number) => `/api/interns/my-weekly-reports/${weekNumber}`,
  // TM-22: Mentor Xem Báo Cáo Tuần & Đánh Giá
  MENTOR_WEEKLY_REPORT_REVIEW: (internCode: string, weekNumber: number) => `/api/mentors/my-interns/${internCode}/weekly-reports/${weekNumber}`,
  MENTOR_REQUEST_REPORT_REVISION: (internCode: string, weekNumber: number) => `/api/mentors/my-interns/${internCode}/weekly-reports/${weekNumber}/request-revision`,
} as const;

